= Nutzungsvorgaben Util

include::partial$library.adoc[]

Die Bibliothek `isy-util` bietet nützliche Hilfsmittel, die von den Anwendungen der IsyFact genutzt werden können.
Es handelt sich dabei um kleinere Utility-Klassen, welche die Implementierung vereinfachen.
Diese werden im Folgenden überblicksartig beschrieben.
Details sind den JavaDoc der einzelnen Klassen zu entnehmen.

[[aufbau-von-isy-util]]
== Aufbau von `isy-util`

[[package-logging]]
=== Package logging

In `de.bund.bva.isyfact.util.logging` sind Klassen enthalten, die für das Logging einzusetzen sind:

* `CombinedMarkerFactory`: Mit dieser Klasse können zusammengesetzte __Marker__ erzeugt werden, die beim Logging mit _slf4j_ verwendet werden können, um Log-Einträge mit Markierungen zu versehen.


[[package-text]]
=== Package text

Das Package `text` enthält Werkzeuge für die Erzeugung standardisierter Ausgabe-Nachrichten:

* `RecursiveToStringBuilder`: Diese Klasse erzeugt eine Textausgabe für Objekte, die keine geeignete `toString`-Methode implementieren.

[[package-persistence]]
=== Package persistence
Das Package `de.bund.bva.isyfact.util.persistence` enthält unterstützende Klassen für den Umgang mit Datenbanken:

* Das Unterpaket `datasource` enthält die Klasse `DataSourceCheck`, mit der Datenbanktabellen auf die richtige Schema-Version geprüft werden können.
Mit der Klasse `ApplicationRunnerDbSchemaCheck` kann diese Prüfung beim Start einer Spring-Anwendung automatisiert werden.

* Die Unterpakete `annotation` und `usertype` enthalten Klassen zum Umgang mit Enum-Entitäten.

[[nutzung-von-isy-util]]
== Utility-Klassen von `isy-util`

[[logging]]
=== Logging-Marker

Mithilfe der statischen Methoden aus der `CombinedMarkerFactory` können Standard-Log-Ausgaben aus `slf4j` markiert werden.

.Markierung einer Log-Ausgabe
[source,java]
[[anwendung-markerfactory]]
----
class Demo {

    void demo() {
        Logger logger = LoggerFactory.getLogger(Demo.class);
        logger.info(createSchluesselMarker("SCHLUESSEL"),"Diese Info-Nachricht ist mit dem Wert aus SCHLUESSEL markiert");
    }

}
----

[[persistence-datasource]]
=== Datasource-Check

[IMPORTANT]
====
Die hier beschriebenen Klassen bewahren die Abwärtskompatibilität zur ehemals in der IsyFact vorhandenen Schema-Versionierung in Form einer Eigenentwicklung.
Die aktuelle Version der IsyFact-Referenzarchitektur empfiehlt hingehen den Einsatz von xref:isyfact-standards-doku:referenzarchitektur:software-technisch/backend/persistenzschicht.adoc#versionierung[Liquibase].
====

Eine Anfrage mit dem `DataSourceCheck` erfolgt über eine der Methoden `checkSchemaVersionCriticalDataSource` oder `checkSchemaVersionNonCriticalDataSource`.
Beide Methoden liefern ein `boolean` zurück, auf das die Applikation entsprechend regieren kann.

[[datasource-check]]
.Durchführung einer Schema-Prüfung
[source,java]
----
class Demo {
    void startUp(DataSource dataSource, String version) {
        DataSourceCheck dsc = new DataSourceCheck();
        if(!dsc.checkSchemaVersionCriticalDatasource(dataSource, version)){
            // handle errors, do logging etc
        }
    }
}
----

Voraussetzung ist die Existenz einer Datenbank-Tabelle, die die aktuelle Schema-Version enthält.
Der `DataSourceCheck` fragt die Tabelle mit einem voreingestellten SQL-Statement ab.

[[check-sql]]
.Abfrage der Schema-Tabelle (Standard)
[source,sql]
----
SELECT version_nummer FROM m_schema_version WHERE version_nummer = ? AND status = 'gueltig'
----

Der <<check-sql>> liegt eine Tabelle in folgender Gestalt zugrunde.

.Beispielhafte Schema-Tabelle
[[table-schema-version]]
[cols="1m,2,3",options="header"]
|====
|Spalte
|Typ
|Beschreibung

|version_nummer
|Zeichenkette (25 Zeichen)
|Versionsnummer des Datenbankschemas.
Diese Versionsnummer entspricht der Versionsnummer der Anwendung, mit der sich das Schema geändert hat.

|update_nummer
|Zeichenkette (5 Zeichen)
|Update-Zähler, der jedes Mal hochgezählt wird, wenn sich das Datenbankschema ändert, aber die Anwendung unverändert bleibt.

|status
| Zeichenkette (25 Zeichen)
a|
`gueltig`:: Das Schema wurde korrekt installiert bzw. aktualisiert und kann verwendet werden.
`ungueltig`:: Das Schema befindet sich im Aufbau bzw. in der Änderung oder die Installation wurde nur teilweise durchgeführt und wurde mit Fehlern abgebrochen.
Das Schema kann nicht verwendet werden und muss überprüft werden.
|====

Andere Formen der Schema-Tabelle können ebenfalls verwendet werden.
In diesem Fall muss bei der Erzeugung das `DataSourceCheck` die geeignete SQL-Abfrage als Parameter angegeben werden.

Für Spring-Anwendungen existiert der Wrapper `ApplicationRunnerDbSchemaCheck`, der als Spring-Komponente hinzugefügt wird und als Implementierung eines `ApplicationRunner` nach vollständiger Initialisierung der Spring-Anwendung den Check automatisch durchführt.


[[enum-variablen]]
=== Enum-Variablen und Annotations

Zum vereinfachten Umgang mit Enum-Variablen im Zusammenhang mit Datenbanken steht die Annotation `PersistentValue` zur
Verfügung.

[[definition-enumusertype]]
[source,java]
----
public enum Richtung {

    @PersistentValue("L")
    LINKS,
    @PersistentValue("R")
    RECHTS,
    @PersistentValue("G")
    GERADEAUS

}
----

Die Klasse `EnumWithIdUserType` erlaubt die Persistierung von Enums, die einen fachlichen Schlüssel besitzen.

[[definition-enumwithidusertype]]
.Definition eines Enums zur Verwendung mit `EnumWithIdUserType`
[source,java]
----
public enum RichtungMitId {

    LINKS("L"),
    RECHTS("R"),
    GERADEAUS("G");

    private final String id;

    RichtungMitId(String id) {
        this.id = id;
    }

    @EnumId
    public String getId() {
        return id;
    }

}
----

Das folgende Beispiel zeigt die Verwendung dieser Enums in einer Entität.

[[verwendung-enum-in-entitaeten]]
.Verwendung von Enums in Entitäten
[source,java]
----
@Entity
public class MyEntity {

  @Column(nullable = false, length = 1)
  @Type(type = "de.bund.bva.isyfact.persistence.usertype.EnumUserType",
    parameters = { @Parameter(name = "enumClass",value = "<package>.Richtung") })
  private Richtung richtung;

  @Column(nullable = false, length = 1)
  @Type(type = "de.bund.bva.isyfact.persistence.usertype.EnumWithIdUserType",
    parameters = { @Parameter(name = "enumClass",value = "<package>.RichtungMitId") })
  private RichtungMitId richtungMitId;

}
----
